services:
  wiki:
    image: ghcr.io/sisi-wiciel/dpd-wiki:latest
    container_name: dpd-wiki
    restart: unless-stopped
    ports:
      - "3002:80"
    labels:
      - "com.dpdr.sns=subdomain:wiki"
